//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nosql
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int id { get; set; }
        public string title { get; set; }
        public Nullable<int> author { get; set; }
        public string price { get; set; }
        public string country { get; set; }
    
        public virtual Author Author1 { get; set; }
    }
}
